[[headers]]
    for = "/*"
    [headers.values]
        Content-Security-Policy = "default-src 'self' mandelbrot.cyberhd1811.de; style-src-elem 'self' fonts.googleapis.com; connect-src 'self' fonts.gstatic.com; font-src 'self' fonts.gstatic.com"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200