[[headers]]
    for = "/*"
    [headers.values]
        Content-Security-Policy = "default-src 'self' mandelbrot.cyberhd1811.de; style-src-elem 'self' fonts.googleapis.com; font-src 'self' fonts.googleapis.com"